linters:
  disable-all: true
  enable:
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - fatcontext
    - forbidigo
    - gochecknoinits
    - gochecksumtype
    - gocritic
    - gofmt
    - goheader
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - inamedparam
    - ineffassign
    - intrange
    - loggercheck
    - mirror
    - nakedret
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tenv
    - testableexamples
    - testifylint
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint
