services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./gen/http/openapi3.yaml:/etc/swagger/swagger.yaml
    environment:
      SWAGGER_JSON: /etc/swagger/swagger.yaml
    ports:
      - "8080:8080"
    restart: on-failure

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/go/src/shiharai-kun
    working_dir: /go/src/shiharai-kun
    ports:
      - "8081:8081"
    restart: on-failure
